### ISSUE TITLE
blocksize

### ISSUE THREAD

**Issue by bioharz** [ArweaveTeam/arweave#12]
I'm mining ar for few days(mining address: qFzYCl02V2De6b0KVvBKThRI01Xw84r_XVZ1_0XXt98) and I have noticed that the blocks are full with ALL ar addresses. Seriously? That doesn't scale at all. I can easily spam the hole network with creating new low balance Addresses.
If nobody write me back, I will stress test the network the next few days.
{"network":"arweave.N.1","version":3,"height":14590,"current":"iEP_8U9N4wSvjt59AFVZeWAqIYEhNsu7KDc5CYdFxcYuHv5AhqaC94PYSDqLh_60","blocks":15842,"peers":83,"queue_length":0}
block  14596_WJMN57VvUQII2CXPqGFPY0KX8HaRcDVZIvqox58RIm2Lm_DXS9x_7OJYWz7dWIxm  has a size of:
1247002 bite
that equals  1.2MB!
for one block!
Nobody is using AR and we already creating 1.2MB blocks?
every 120 sec?
the blockchain size is already over 10GB!

**Comment by samcamwilliams** [comment]
Hi,

This issue was discussed and resolved via Discord.

The key misunderstanding was that every node in the blockweave is *not* required to store every block. Nodes compete for mining rewards with their storage space. The more blocks you have, the more likely you are to gain a reward.

You can read more about the blockweave data structure and Proof of Access mining mechanism in our lightpaper: https://arweave.org/files/arweave-lightpaper.pdf .

Best regards,
Sam
