### ISSUE TITLE
Configuration via file

### ISSUE THREAD

**Issue by themue** [ArweaveTeam/arweave#22]
Today configuration of a node is done via command line arguments. Depending on the number of non-default arguments as well as initial peers the list ist long, inconvenient, and error prone.

Defining them in a configuration file improves this. Additionally templates for own configurations can be provided.

The format is to be discussed:

- Erlang/OTP terms
- Different standard formats like JSON, YAML, or TOML
- Propriatary formats

**Comment by codybartfast** [comment]
Another advantage of a config file is that it could be shared be shared between Linux and native Windows without having to remove/convert line continuation marks.

It would be nice if any config file could be shared between mines and other Arweave applications.  E.g., I presume many Arweave applications and clients would need a list of peers. Even if the config file couldn't be shared, a common style would still be a benefit.  For that reason, I'm inclined against Erlang/OTP Terms (not that I'm familiar with it).

Unless there's a significant advantage to YAML or TOML (I'm not familiar with them either!) then JSON seems like a natural choice because it's ubiquitous, and many Arweave apps will have to support JSON anyway to handle keys.

**Comment by majastanislawska** [comment]
OTP's application.config.
This codebase cries for OTP especially that boys want it as platform for other apps.
having it embeddable as rebar dep or starting with erl -s ar would be advantage.

**Comment by codybartfast** [comment]
Thank you @majastanislawska 

In a sense I suspect JSON is 'technically' the least good option.  But if a config file becomes the 'user interface' then I think familiarity among non-Erlangers should be a factor to weigh in the scales.

Also, it might be worth distinguishing between data that is related to the Erlang implementation (Prometheus?) vs data that has a wider use (peer lists, black lists?) that might benefit from a ubiquitous, portable format.

I'm not a particular fan of JSON - I'm just lazy ;-)

**Comment by majastanislawska** [comment]
User interface of this is dead simple it's just a list of KVP's.
Argument for portable format is pointless unless there is implementation of that in different language, which would have it's own configuration specifics anyway.
If You are lazy than .config is perfect choice. it's already builtin and it's well tested by generations of engineers.
You have several layers of defaults gathering, embeding extra configfiles and overwriting config params from cmdline builtin alrady.
let's not try reinvent wheel.

**Comment by codybartfast** [comment]
Hi, I am not an Erlang developer and I don't plan to be one anytime soon, even if had the ability.  I'm commenting because I think this is an example where my ignorance about Erlang gives me a different perspective.

My first hat is as a miner.  Today my user interface is the command line.  I would prefer a config file, and given a choice, as the user of the application, I would prefer to use JSON because I know it.

I'm just mining for the laughs™, but if I were  more serious I might be writing utilities to read (or write)  the config (e.g. location of the blocks folder, max cores to use, disk limits).  If it's JSON then that's familiar to most admins and devs.

I appreciate that serious miners will likely to need to learn more about the Erlang ecosystem but it would be good to be able to get started without it.

I'm also playing at writing some .Net client utilities, the wallet is JSON and all the Web API responses are JSON, so when I need to store some configuration data, like seed peer addresses, I will use JSON.  But also, when I can, I'll use the same style as the web api.  The peers list in my app's config will be in the _exact_ same format as the peers returned by the web api, then I can use the same code to parse either of them.  So it seems natural to me, from the outside, to think the list of peers in a server config file might be in that format too.

There's a subset of configuration data like port, wallet-address, peers, number of cpu, disk limits, data location that is likely common to any mining application and to many other weave related apps,  and I think there's a benefit if the common data is in a common format.

But since I won't be doing the PR it won't be my call ;-)

**Comment by majastanislawska** [comment]
I like your attitude, lets pick json, brecause its only thing you know about and you're too lazy to find out yourself that config in erlang terms wouldn't be much different afterall.
There is way more behind my proposal than how configfile would actually look like, but since you don't plan to be erlang developer, there is no point going deeper.
Yeah, blocks are stored on disk in json too.
Some people should be taught that there is so much more in this industry than just json.
Don't get me wrong, i love json, for one reason - it effectively killed xml. 
10 years ago this codebase would be farting xml  and soap everywhere. 
every generation have its own mental blockades. now its time for json and web apis.
you will grow up from those.
eventually.

**Comment by codybartfast** [comment]
I expect you're absolutely right that Erlang terms is the right tool for configuring the application.  And, the last thing I'm suggesting is that the whole of the system's configuration should be in JSON.  

My point is that there are probably only a dozen configuration options that most miners and will ever use, they could be stored in JSON and that would make the application easier to use and program against (which I think is a good thing).  I can't imagine it would be that hard to map those dozen options from JSON to Erlang terms to integrate with the rest of the configuration.

If it's not practical fine, I think it's perfectly reasonable to say a dual configuration is an unnecessary complexity, I'm just saying that whatever the disadvantages of JSON it does have the advantage of ubiquity and familiarity.

And yes, "use X because it's ubiquitous" is a very dangerous argument.  It's why (in my opinion) the world still has to endure the fundamentally broken, so called, 'object orientated' languages like Java and C#, but that's a whole other debate.  Actually, I do intend to learn Erlang and I only got interested in this project via my vicarious interest in it, but currently I'm also learning Scheme and F# and so Erlang (or possibly Elixir) will have to wait for now.
