### ISSUE TITLE
[build] Error 127

### ISSUE THREAD

**Issue by KA-Software** [ArweaveTeam/arweave#31]
Hi I am using Mac (latest update) and facing following problem by starting a mining process:

`git submodule update --init
Submodule 'lib/accept' (https://github.com/deadtrickster/accept.git) registered for path 'lib/accept'
Submodule 'lib/prometheus' (https://github.com/deadtrickster/prometheus.erl.git) registered for path 'lib/prometheus'
Submodule 'lib/prometheus_process_collector' (https://github.com/deadtrickster/prometheus_process_collector.git) registered for path 'lib/prometheus_process_collector'
Cloning into '/Users/Konstantin/arweave/lib/accept'...
Cloning into '/Users/Konstantin/arweave/lib/prometheus'...
Cloning into '/Users/Konstantin/arweave/lib/prometheus_process_collector'...
Submodule path 'lib/accept': checked out '9b52b6c5e23f32feccca9bb187913a4fe3ca7865'
Submodule path 'lib/prometheus': checked out 'e7744268131c63d666cf1413cabf4f620b918ba9'
Submodule path 'lib/prometheus_process_collector': checked out 'bad06f50e36f246db170f84b73a5d97960a75f26'
rm -rf priv
rm -rf data/mnesia
cd lib/jiffy && ./rebar compile && cd ../.. && mv lib/jiffy/priv ./
env: escript: No such file or directory
make: *** [build] Error 127`

Previously I got a following message, don't know if this is an issue
`HEAD is now at 87fccde - Verify full block download before adding txs in ar_http_iface:get_full_block.`

**Comment by themue** [comment]
Hi, would you mind adding some more information on your installation and on the steps before this error happened? How did you install Erlang (e.h. Homebrew) and what do `which escript` and `which erlc` return. Thanks

**Comment by samcamwilliams** [comment]
Closed due to non-response. Will re-open if we receive any other instances of this issue, or further information.

**Comment by UndiFineD** [comment]
READ
https://docs.arweave.org/info/mining/mining-guide
especially “The number of available file descriptors”

$ sudo ulimit -n
1000000

$ apt-get install erlang git build-essential

$ mkdir mining/arweave
$ wget https://github.com/ArweaveTeam/arweave/archive/refs/tags/stable.tar.gz
$ mv stable.tar.gz arweave-2.4.3.0.linux-x86_64.tar.gz



$ nano start.sh

#---------------
#!/bin/bash
export PATH=/volume1/@appstore/erlang/bin/:$PATH
cd mining/arweave
sh mining/arweave/bin/start-dev YOUR-MINING-ADDRESS peer 188.166.200.45 peer 188.166.192.169 peer 163.47.11.64 peer 139.59.51.59 peer 138.197.232.192
#---------------

$ chmod +x start.sh
$ sh start.sh 

Building dependencies...
===> Verifying dependencies...
===> Fetching b64fast (from {git,"https://github.com/ArweaveTeam/b64fast.git",
                   {ref,"a0ef55ec66ecf705848716c195bf45665f78818a"}})
===> Fetching pc (from {git,"https://github.com/blt/port_compiler.git",{tag,"v1.12.0"}})
===> Analyzing applications...
===> Compiling pc
===> Fetching cowboy v2.9.0
===> Fetching graphql (from {git,"https://github.com/shopgun/graphql-erlang.git",
                   {ref,"fc76a2df7d1ddcf8bcc3bb46363e7ca8fca80939"}})
===> Fetching geas_rebar3 (from {git,"https://github.com/crownedgrouse/geas_rebar3.git",
                       {branch,"master"}})
===> Fetching geas v2.7.5
===> Fetching samovar v1.0.2
===> Analyzing applications...
===> Compiling samovar
===> Compiling geas
===> Compiling geas_rebar3
===> Fetching rebar3_hex v6.11.6
===> Fetching hex_core v0.7.1
===> Fetching verl v1.0.2
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
===> Fetching gun v1.3.2
===> Fetching jiffy v1.0.8
===> Fetching prometheus v4.6.0
===> Fetching rebar3_archive_plugin v0.0.1
===> Fetching rebar3_elvis_plugin (from {git,"https://github.com/deadtrickster/rebar3_elvis_plugin.git",
                               "master"})
===> WARNING: It is recommended to use {branch, Name}, {tag, Tag} or {ref, Ref}, otherwise updating the dep may not work as expected.
===> Fetching katana_code v0.1.0
===> Fetching zipper v1.0.1
===> Fetching aleppo v1.0.0
===> Analyzing applications...
===> Compiling aleppo_build/default/plugins/aleppo/src/aleppo.erl:6: Warning: record ale_context has field(s) without type information
_build/default/plugins/aleppo/src/aleppo.erl:12: Warning: missing specification for function process_file/1
_build/default/plugins/aleppo/src/aleppo.erl:15: Warning: missing specification for function process_file/2
_build/default/plugins/aleppo/src/aleppo.erl:25: Warning: missing specification for function process_tokens/1
_build/default/plugins/aleppo/src/aleppo.erl:32: Warning: missing specification for function process_tokens/2
_build/default/plugins/aleppo/src/aleppo.erl:307: Warning: missing specification for function scan_file/1

===> Compiling zipper
===> Compiling katana_code
===> Compiling rebar3_elvis_plugin
===> Analyzing applications...
===> Compiling rebar3_archive_plugin
===> Fetching prometheus_cowboy v0.1.8
===> Fetching prometheus_process_collector v1.6.0
===> Fetching rocksdb (from {git,"https://gitlab.com/arweave1/erlang-rocksdb.git",
                   {ref,"cba9ec42255862196bec35b7ddcbdf8feedf4277"}})
===> Fetching cowlib v2.8.0
===> Fetching prometheus_httpd v2.1.11
===> Fetching ranch v1.8.0
===> Fetching accept v0.3.5
+ mkdir -p _build/cmake
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ cmake ../../c_src
/volume1/homes/undifined/arweave/_build/default/lib/rocksdb/do_cmake.sh: line 12: cmake: command not found
+ exit 1
===> Hook for compile failed!

And missing “ build-essential “ has stopped me from running on synology thusfar

**Comment by UndiFineD** [comment]
which is weird, because it seems to be there
find / -name "cmake"
arweave/_build/default/lib/rocksdb/deps/rocksdb/cmake
arweave/_build/default/lib/rocksdb/deps/snappy/cmake
arweave/_build/default/lib/rocksdb/_build/cmake

**Comment by mcmonkeys1** [comment]
You could try installing from apt.
What CPU are you using? It may not be ideal for Arweave mining.

https://discord.gg/N36hEczV

You can join the official Arweave Miners chat server for further clarification.
