### ISSUE TITLE
Congestion: often my data transactions return "pending" and then later "not found"? 

### ISSUE THREAD

**Issue by 1618employment** [ArweaveTeam/arweave#353]
I'm guessing this is a "congestion issue"?

It appears you know this is a problem because it was mention in your last release...

> Transactions are not rejected when the mempool limit is reached; instead, the least valuable transactions are dropped from the memory pool;

Arweave appears to use a mempool, does it?

Arweave appears to drop transactions that don't get included in the next block, does it?

Why dropped?

Why don't transactions stay pending indefinitely so theoretically when congestion ebbs they get mined?

I've notice at the time my txs are being dropped most of the other pending transaction have a much higher, almost purposefully chosen, but still seeming arbitrary "network fee".

Can someone point me to the documentation regarding how Arweave handles congestion?

Is there an undocumented HTTP API for congestion somewhere?

How would one create a metric in their own app for determining a better network fee than GetPrice() which appears to be "inadequate"?

`query graph for last 200 data transactions AND network fee / data size
`

Is there a queryable metric like average fee per byte per block available from an explorer api somewhere?

Network fee slider?

But again this seems like arbitrary and "guessing" if the current state of network congestion at the time of transaction can't be determined.

Doing what all the NFT junkies are doing and picking a randomly higher network fee that gets me in the next block seems lazy and lame!

Thanks, keep up the good work!

**Comment by 1618employment** [comment]
I just read about bundlers and I'm guessing some genius is going to tell me to bundle.

Let me see if I get this right...your solution to an L1 congestion problem is to prioritize more rewarding (larger) transactions, drop transactions that don't make the cut, and push an L2 solution which is basically an aggregator (increases the tx reward and prioritization by bundling) and has to stake tokens, so basically a DASH masternode? Very original and democratic!

So your adding centralization and an additional point of complexity, failure, hack, and/or censorship? Hope nobody loses their tokens!

So am I still allowed to send L1 transactions? Current propaganda would indicate nyet...

Can I get the solution behind door L1 please?

**Comment by ldmberman** [comment]
Hi,

> Why don't transactions stay pending indefinitely so theoretically when congestion ebbs they get mined?

A transaction may stay pending for up to 50 blocks (~100 minutes) because it needs to reference one of the last 50 blocks. This is a measure against filling up the mempools with transactions for free.

How do you upload transactions? Note that v1 (the "format" field is 1) transactions are prioritized much lower, v2 is the recommended format - the congestions happen relatively infrequently with the v2 transactions so far.

If it does happen to you, then as a workaround, you may fetch the mempool transaction identifiers from a node via `GET /tx/pending` (`https://arweave.net/tx/pending` also works). The list is sorted, higher-reward transactions come first. To know the fee of a particular tx, use `GET /unconfirmed_tx/[txid]`. You may, e.g., start from the middle of the list and do the binary search until you find the biggest-fee transaction smaller than some maximum that you are ready to pay. I would also ask around on our [dev community server](https://discord.gg/6ekMutmA) if somebody has created some tooling for finding a better fee.

> So your adding centralization and an additional point of complexity, failure, hack, and/or censorship?

Having more complexity in the base protocol is even riskier considering failures and hacks. As for centralization and censorship resistance, it is a trade-off, yes. However, it does not affect the confirmed data.

**Comment by 1618employment** [comment]
Thank you for that response, the solution you suggested with pending definitely works. Yes v2, it happens most often when my transaction are storing a small amount of data and sending a small amount of AR, so definitely low priority. I will look into bundling these lower priority transactions.

What is the determinant for a block or mempool being "full"? Is it the number of transactions or the total size of bytes?

I should point out there is a reporting discrepancy between  the viewblock.io explorer and graphQL queries. For example [viewblock.io](https://viewblock.io/arweave/block/887262) reports block# 887262 has 260 transactions, but running a graphQL query for that block reported 8050 transactions?

Any ideas why this might be? Are bundled transactions consider a single transaction?

I'd like to understand historic fees in order to more accurately predict future fees. Thank you!
