### ISSUE TITLE
Official Arweave Not Working properly

### ISSUE THREAD

**Issue by mayank-daga** [ArweaveTeam/arweave#524]
Hi, 
Any idea why official arweave api: https://arweave.net/current_block doesn't work properly. Yesterday it was not working today it started working.

**Comment by hlolli** [comment]
please explain what you mean by not working properly?

**Comment by mayank-daga** [comment]
Hi @hlolli also I am getting Forbidden for the same api https://arweave.net/block.height/1 when i am requesting from code

**Comment by vird** [comment]
https://arweave.net/block/height/1

**Comment by mayank-daga** [comment]
Hi @vird I had used this one only it doesnot work any other third party api avialable for areweave

**Comment by hlolli** [comment]
You need to give us reproduceable problem, or at very minimum, a verbose logging of a request you are doing, both request and response, from postman or curl. Otherwise there's nothing we can do to help. Of millions of daily arweave users, nobody's having issue at the moment @mayank-daga so this must be a very rare or mysterious issue you are having

**Comment by mayank-daga** [comment]
ok thanks @vird @hlolli for your support closing this issue
